# Generated by Django 3.2.7 on 2021-12-19 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=12, verbose_name=django.db.models.deletion.SET_NULL),
        ),
    ]
