# Generated by Django 3.2.7 on 2022-03-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='loginpassword',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='loginusername',
        ),
    ]
